services:
  escoly-mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: escoly-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escoly 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  mysql: