version: '3.8'
services:
  escoly-mysql-db:
    image: mysql
    env_file: ./.env
    container_name: escoly-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE 
    ports:
      - $MYSQL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  mysql:
