version: '3.8'
services:
  escoly-mysql-db:
    image: mysql
    env_file: ./.env
    container_name: escoly-mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE 
    ports:
      - $MYSQL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  escoly-app:
    build: .
    env_file: ./.env
    container_name: escoly-app
    depends_on:
      - escoly-mysql-db
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "if [ \"$NODE_ENV\" = \"dev\" ]; then npm run start dev; else npm run start; fi"] 
    environment:
      MYSQL_HOST: escoly-mysql
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_DATABASE: $MYSQL_DATABASE
volumes:
  mysql_data:
    name: mysql_data 
